spring:

  datasource:
    url: jdbc:h2:mem:maindb

  sql:
    init:
      mode: never
      data-locations: data.sql
      schema-locations: schema.sql

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    contexts: hw05

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    ROOT: ERROR